name: aquaverse
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  cached_network_image: ^3.4.1
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.12.0
  google_nav_bar: ^5.0.7
  supabase_flutter: ^2.12.0
  shared_preferences: ^2.2.2
  flutter_launcher_icons: ^0.14.4
  flutter_unused_packages: ^1.0.1
  intl: ^0.19.0
  flutter_map: ^8.2.2
  latlong2: ^0.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"

flutter:
  uses-material-design: true

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-Light.ttf
          weight: 300

    - family: Afacad
      fonts:
        - asset: assets/fonts/Afacad-Regular.ttf
          weight: 400
        - asset: assets/fonts/Afacad-SemiBold.ttf
          weight: 600

    - family: Agbalumo
      fonts:
      - asset: assets/fonts/Agbalumo-Regular.ttf
        weight: 400



